### ISSUE TITLE
Criar vários eventos e definir os modos de jogo

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/TitansBattle#11]
### Sugestão

Adicionar um sistema onde é possível criar vários modos de jogo e não apenas 4.

#### Exemplo:

Dentro da pasta games criar um `.yml` com nome do evento.

├── Plugins
  ├── TitansBattle
    ├── games
      └── \<evento>.yml

Usando `gladiador.yml` você poderia configurar todo o evento com sua própria arena, traduções, kits e etc..

```yml
#Nome do evento
game_name: Gladiador

#Modo de jogo
game_type: FREEFORALL_FUN

#Game announcements
announcements:
  #Before the game starts, how much messages will be sent to players and how much time between them?
  starting:
    times: 2
    interval: 30
  #Insert the interval of the message with informations of the game
  game_info:
    interval: 30

#Minimum to start the game
minimum:
    players: 10

#The time to finish the game if no one wins (in seconds)
expiration_time: 3600

#The time for the players to gegt ready
preparation_time: 30

#If join/quit messages are on and the player is both killer and winner, choose wich one will be used
join_or_quit_message_priority: KILLER #Available option: KILLER | WINNER

#Should join/quit messages be sent when a winner/killer joins the server?
winner-quit-message: true

winner-join-message: true

killer-quit-message: true

killer-join-message: true

#Inventory the players will get to use
kit:

#Prizes for the winners
prizes:
    #If player's inventory is full, this is the frequency in seconds to ask to clear the inventory
    items_give_interval: 30
    members:
        items:
            enabled: false
            item_list:
        commands:
            enabled: false
            some_number:
                value: 10
                divide: true
            command_list: ["give %player% diamond_sword %some_number%", "eco give %player% %some_number%"]
        money:
            enabled: false
            divide: false
            amount: 10000.0
            
#Destinations used by the plugin
destinations:
    exit:
    lobby:
    watchroom:
    arena:      
    
#Hooks configuration
hooks:
  #If you use Legendchat, add {tb_freeforallfun_killer} and {tb_freeforallfun_winner} in its chat format settings
  legendchat:
      killer:
          prefix: "[Killer] "
      winner:
          prefix: "[Winner] "

#Use this to set a specific message for this game mode.
language:
    #Since it is a non-group game, these messages in their original form would make no sense
    watch_to_the_end: " "
    winners: "&a[TitansBattle] The current winners are:\nKiller: {0}\nWinner: {2}"
    who_won: "&a[TitansBattle] Game over! The winner is: {0}."
    not_enough_participants: "&a[TitansBattle] There was not enough players to start the game!"
    game_info: "&a[TitansBattle] There is {0} players participating!"
    starting_game: "&a[TitansBattle] Starting game in {0} seconds! Join using /tb join.\nNeeded: {2} players\nParticipating: {4} players."
```

### Motivo

Com essa mudança seria possível criar diversos tipos de batalhas e não somente Gladiador.
