### ISSUE TITLE
Adicionar Blacklist de itens

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/TitansBattle#35]
Adicionar opção de blacklist de itens que podem estar no inventário ao entrar em um evento.

**Comment by RoinujNosde** [comment]
Você quis dizer whitelist, né?
```yml
whitelist:
- BOW
- ARROW
```
Consegue entrar apenas com arco e flechas.

**Comment by SrBedrock** [comment]
Eu estava pensando mais em uma blacklist porque queria impedir a entrada de alguns itens como por exemplo: `EXPERIENCE_BOTTLE`

Que tal um toggle onde pode se tornar whitelist ou blacklist?

Exemplo:
```yml
# Should whitelist option act as a blacklist?
blacklist: false
whitelist:
- BOW
- ARROW
```
