### ISSUE TITLE
Adicionar opção para executar comandos

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/TitansBattle#4]
### Sugestão

Opção para executar comandos pré-definidos na configuração no inicio de cada etapa do evento como por exemplo ao iniciar o tempo de preparação.

**Exemplo:**

```yml
#The time for the players to get ready
preparation_time: 30

#Comandos a serem executados no incio da preparação
command_preparation: ["effect give %player% minecraft:invisibility 1000 1 true"]

#If join/quit messages are on and the player is both killer and winner, choose wich one will be used
join_or_quit_message_priority: KILLER #Available option: KILLER | WINNER
```
