### ISSUE TITLE
Erro quando é definido vencedor do evento

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/TitansBattle#69]
Ao definir um vencedor do evento com o comando `/tb setwin [jogador]`, todos os jogadores vivos na partida recebem o prêmio definido para o primeiro colocado.

Exemplo do prêmio:
```yml
  prizes:
    FIRST:
      ==: prize
      items_give_interval: 30
      leader.commands.command_list:
      - give %player% diamond_sword %some_number%
      - eco give %player% %some_number%
      leader.commands.enabled: false
      leader.commands.some_number.divided: false
      leader.commands.some_number.value: 100.0
      leader.items.enabled: false
      leader.items.item_list: null
      member.commands.command_list:
      - eco give %player% 50000
      member.commands.enabled: true
      member.commands.some_number.divided: false
      member.commands.some_number.value: 100.0
      member.items.enabled: false
      member.items.item_list: null
      treat_leaders_as_members: true
    SECOND:
      ==: prize
      items_give_interval: 30
      leader.commands.command_list:
      - give %player% diamond_sword %some_number%
      - eco give %player% %some_number%
      leader.commands.enabled: false
      leader.commands.some_number.divided: false
      leader.commands.some_number.value: 100.0
      leader.items.enabled: false
      leader.items.item_list: null
      member.commands.command_list:
      - give %player% diamond_sword %some_number%
      - eco give %player% %some_number%
      member.commands.enabled: false
      member.commands.some_number.divided: false
      member.commands.some_number.value: 100.0
      member.items.enabled: false
      member.items.item_list: null
      treat_leaders_as_members: false
    THIRD:
      ==: prize
      items_give_interval: 30
      leader.commands.command_list:
      - give %player% diamond_sword %some_number%
      - eco give %player% %some_number%
      leader.commands.enabled: false
      leader.commands.some_number.divided: false
      leader.commands.some_number.value: 100.0
      leader.items.enabled: false
      leader.items.item_list: null
      member.commands.command_list:
      - give %player% diamond_sword %some_number%
      - eco give %player% %some_number%
      member.commands.enabled: false
      member.commands.some_number.divided: false
      member.commands.some_number.value: 100.0
      member.items.enabled: false
      member.items.item_list: null
      treat_leaders_as_members: false
    KILLER:
      ==: prize
      items_give_interval: 30
      leader.commands.command_list:
      - give %player% diamond_sword %some_number%
      - eco give %player% %some_number%
      leader.commands.enabled: false
      leader.commands.some_number.divided: false
      leader.commands.some_number.value: 100.0
      leader.items.enabled: false
      leader.items.item_list: null
      member.commands.command_list:
      - give %player% diamond_sword %some_number%
      - eco give %player% %some_number%
      member.commands.enabled: false
      member.commands.some_number.divided: false
      member.commands.some_number.value: 100.0
      member.items.enabled: false
      member.items.item_list: null
      treat_leaders_as_members: false
 ```
