### ISSUE TITLE
Permitir o uso de Placeholders nas configurações

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/TitansBattle#70]
Integrar Placeholders do PlaceholderAPI para que possa ser usado nas configurações, exemplo de uso:

Exemplo usando a expansão [Server](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#server)e o comando do [EssentialsX](https://github.com/EssentialsX/Essentials):
```yml
  prizes:
    FIRST:
      ==: prize
      items_give_interval: 30
      leader.commands.command_list: null
      leader.commands.enabled: false
      leader.commands.some_number.divided: false
      leader.commands.some_number.value: 100.0
      leader.items.enabled: false
      leader.items.item_list: null
      member.commands.command_list:
      - "give %player% bow name:Super_Arco lore:Vencedor_do_Evento_Arqueiro|Data: %server_time_dd/MM/YY%"
      member.commands.enabled: true
      member.commands.some_number.divided: false
      member.commands.some_number.value: 100.0
      member.items.enabled: false
      member.items.item_list: null
      treat_leaders_as_members: true
```

Exemplo usando a expansão do [SimpleClans](https://github.com/RoinujNosde/SimpleClans) e comando do [EssentialsX](https://github.com/EssentialsX/Essentials):
```yml
  prizes:
    FIRST:
      ==: prize
      items_give_interval: 30
      leader.commands.command_list: null
      leader.commands.enabled: false
      leader.commands.some_number.divided: false
      leader.commands.some_number.value: 100.0
      leader.items.enabled: false
      leader.items.item_list: null
      member.commands.command_list:
      - "give %player% dragon_egg name:%simpleclans_tag_label%_%simpleclans_clan_name% lore:Troféu_da_Guerra_de_Clãs|Data:_%server_time_dd/MM/YY%"
      member.commands.enabled: true
      member.commands.some_number.divided: false
      member.commands.some_number.value: 100.0
      member.items.enabled: false
      member.items.item_list: null
      treat_leaders_as_members: true
```
