### ISSUE TITLE
[Sugestão] Salvar data em um arquivo separado do config.yml

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/TitansBattle#76]
Salvar informações de data em um arquivo separado para que seja possível o compartilhamento do arquivo entre servidores diferente e para que facilite a exclusão de configurações quando necessário.

Linhas no config.yml:
```yml
data:
  respawn:
  clear_inv:
```
